In [1]:
# ============================================================
# COVID-19 Global Trends Analysis
# Notebook 2: SQL Analysis with PostgreSQL
# Author  : Udit Jadli
# Date    : March 2026
# ============================================================


# ============================================================
# SECTION 6 - SQL ANALYSIS
# ============================================================


# ---- 6.1 Setup PostgreSQL Connection ----

# These libraries help us talk to PostgreSQL from Python
import psycopg2                        # used to connect to PostgreSQL
from sqlalchemy import create_engine   # used to load our data into PostgreSQL tables
import pandas as pd                    # used to read our cleaned CSV files

# Fill in the connection details for our local PostgreSQL database
DB_NAME     = 'covid19_db'   # the database we created earlier in pgAdmin
DB_USER     = 'postgres'     # default username for PostgreSQL
DB_PASSWORD = 'admin123'     # password we set in pgAdmin
DB_HOST     = 'localhost'    # our database is running on this same computer
DB_PORT     = '5432'         # PostgreSQL always runs on this port by default

# Build the connection string and create an engine
# Think of the engine as a bridge between Python and our PostgreSQL database
engine = create_engine(
    f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
)

# Try connecting to make sure everything is working before we load any data
with engine.connect() as connection:
    print(" Connected to PostgreSQL successfully!")
    print(f"   Database : {DB_NAME}")
    print(f"   Host     : {DB_HOST}")
    print(f"   Port     : {DB_PORT}")

 Connected to PostgreSQL successfully!
   Database : covid19_db
   Host     : localhost
   Port     : 5432

In [2]:
# ---- 6.2 Load Cleaned Data into PostgreSQL ----

import os

# Path to our cleaned CSV files
PROCESSED_PATH = '../data/processed/'

# List of cleaned files we want to load into PostgreSQL
# Each file will become a table in our covid19_db database
tables = {
    'country_wise'  : 'country_wise_latest_cleaned.csv',
    'covid_clean'   : 'covid_19_clean_complete_cleaned.csv',
    'day_wise'      : 'day_wise_cleaned.csv',
    'full_grouped'  : 'full_grouped_cleaned.csv',
    'worldometer'   : 'worldometer_data_cleaned.csv'
}

# Loop through each file and load it into PostgreSQL as a table
for table_name, file_name in tables.items():
    # Read the cleaned CSV file into a dataframe
    df = pd.read_csv(f'{PROCESSED_PATH}{file_name}')

    # Load the dataframe into PostgreSQL as a table
    # if_exists='replace' means if the table already exists, replace it
    # index=False means don't add an extra index column
    df.to_sql(table_name, engine, if_exists='replace', index=False)

    print(f" {table_name} loaded into PostgreSQL ({len(df)} rows)")

print("\n All tables loaded into PostgreSQL successfully!")

 country_wise loaded into PostgreSQL (187 rows)
 covid_clean loaded into PostgreSQL (49068 rows)
 day_wise loaded into PostgreSQL (188 rows)
 full_grouped loaded into PostgreSQL (35156 rows)
 worldometer loaded into PostgreSQL (209 rows)

 All tables loaded into PostgreSQL successfully!

In [4]:
# ---- 6.3 Basic SQL Queries ----

# Helper function to run any SQL query and return results as a dataframe
def run_query(query, description):
    # Print the query description so we know what we are looking at
    print(f"\n{'='*55}")
    print(f" {description}")
    print(f"{'='*55}")
    # Run the query and load results into a dataframe
    result = pd.read_sql(query, engine)
    print(result.to_string(index=False))
    return result


# Query 1 - Total confirmed, deaths and recovered globally
run_query("""
    SELECT 
        MAX("Confirmed")  AS total_confirmed,
        MAX("Deaths")     AS total_deaths,
        MAX("Recovered")  AS total_recovered
    FROM day_wise;
""", "Query 1 - Global Totals")


# Query 2 - Top 10 countries by confirmed cases
run_query("""
    SELECT 
        "Country/Region"    AS country,
        "Confirmed"         AS confirmed_cases,
        "Deaths"            AS deaths,
        "Recovered"         AS recovered
    FROM country_wise
    ORDER BY "Confirmed" DESC
    LIMIT 10;
""", "Query 2 - Top 10 Countries by Confirmed Cases")


# Query 3 - Top 10 countries by death rate
run_query("""
    SELECT 
        "Country/Region"            AS country,
        "Deaths / 100 Cases"        AS death_rate,
        "Recovered / 100 Cases"     AS recovery_rate
    FROM country_wise
    ORDER BY "Deaths / 100 Cases" DESC
    LIMIT 10;
""", "Query 3 - Top 10 Countries by Death Rate")

=======================================================
 Query 1 - Global Totals
=======================================================
 total_confirmed  total_deaths  total_recovered
        16480485        654036          9468087

=======================================================
 Query 2 - Top 10 Countries by Confirmed Cases
=======================================================
       country  confirmed_cases  deaths  recovered
            US          4290259  148011    1325804
        Brazil          2442375   87618    1846641
         India          1480073   33408     951166
        Russia           816680   13334     602249
  South Africa           452529    7067     274925
        Mexico           395489   44022     303810
          Peru           389717   18418     272547
         Chile           347923    9187     319954
United Kingdom           301708   45844       1437
          Iran           293606   15912     255144

=======================================================
 Query 3 - Top 10 Countries by Death Rate
=======================================================
       country  death_rate  recovery_rate
         Yemen       28.56          49.26
United Kingdom       15.19           0.48
       Belgium       14.79          26.27
         Italy       14.26          80.64
        France       13.71          36.86
       Hungary       13.40          74.84
   Netherlands       11.53           0.35
        Mexico       11.13          76.82
         Spain       10.44          55.20
Western Sahara       10.00          80.00

          country  death_rate  recovery_rate
0           Yemen       28.56          49.26
1  United Kingdom       15.19           0.48
2         Belgium       14.79          26.27
3           Italy       14.26          80.64
4          France       13.71          36.86
5         Hungary       13.40          74.84
6     Netherlands       11.53           0.35
7          Mexico       11.13          76.82
8           Spain       10.44          55.20
9  Western Sahara       10.00          80.00

In [11]:
# ---- 6.4 Intermediate SQL Queries ----

# Query 4 - Total cases grouped by WHO Region
run_query("""
    SELECT 
        "WHO Region"                AS who_region,
        SUM("Confirmed")            AS total_confirmed,
        SUM("Deaths")               AS total_deaths,
        SUM("Recovered")            AS total_recovered
    FROM country_wise
    GROUP BY "WHO Region"
    ORDER BY total_confirmed DESC;
""", "Query 4 - Total Cases by WHO Region")


# Query 5 - Countries with recovery rate above 70%
run_query("""
    SELECT 
        "Country/Region"            AS country,
        "Recovered / 100 Cases"     AS recovery_rate,
        "Deaths / 100 Cases"        AS death_rate,
        "Confirmed"                 AS confirmed_cases
    FROM country_wise
    WHERE "Recovered / 100 Cases" > 70
    ORDER BY recovery_rate DESC;
""", "Query 5 - Countries with Recovery Rate Above 70%")


# Query 6 - Countries with death rate above 10%
run_query("""
    SELECT 
        "Country/Region"            AS country,
        "Deaths / 100 Cases"        AS death_rate,
        "Confirmed"                 AS confirmed_cases,
        "Deaths"                    AS total_deaths
    FROM country_wise
    WHERE "Deaths / 100 Cases" > 10
    ORDER BY death_rate DESC;
""", "Query 6 - Countries with Death Rate Above 10%")

=======================================================
 Query 4 - Total Cases by WHO Region
=======================================================
           who_region  total_confirmed  total_deaths  total_recovered
             Americas        8839286.0      342732.0        4468616.0
               Europe        3299523.0      211144.0        1993723.0
      South-East Asia        1835297.0       41349.0        1156933.0
Eastern Mediterranean        1490744.0       38339.0        1201400.0
               Africa         723207.0       12223.0         440645.0
      Western Pacific         292428.0        8249.0         206770.0

=======================================================
 Query 5 - Countries with Recovery Rate Above 70%
=======================================================
                         country  recovery_rate  death_rate  confirmed_cases
                        Holy See         100.00        0.00               12
                        Dominica         100.00        0.00               18
                         Grenada         100.00        0.00               23
                        Djibouti          98.38        1.15             5059
                         Iceland          98.33        0.54             1854
                          Brunei          97.87        2.13              141
                     New Zealand          97.24        1.41             1557
                           Qatar          97.02        0.15           109597
                        Malaysia          96.60        1.39             8904
                       Mauritius          96.51        2.91              344
                          Norway          95.84        2.79             9132
                         Taiwan*          95.24        1.52              462
                            Laos          95.00        0.00               20
                           Malta          94.86        1.28              701
                         Estonia          94.54        3.39             2034
                        Thailand          94.36        1.76             3297
                   Liechtenstein          94.19        1.16               86
                      San Marino          93.99        6.01              699
                         Finland          93.54        4.45             7398
                       Greenland          92.86        0.00               14
                            Cuba          92.85        3.44             2532
                          Turkey          92.71        2.48           227019
                         Comoros          92.66        1.98              354
                           Chile          91.96        2.64           347923
                         Germany          91.89        4.41           207112
                     Saint Lucia          91.67        0.00               24
                         Denmark          91.60        4.45            13761
                     South Korea          91.58        2.11            14203
                         Bahrain          91.46        0.36            39482
                           China          90.88        5.37            86783
                           Niger          90.72        6.10             1132
                         Ireland          90.24        6.81            25892
                         Belarus          89.95        0.80            67251
                       Singapore          89.88        0.05            50838
                          Monaco          89.66        3.45              116
                     Switzerland          89.62        5.74            34477
                         Austria          88.75        3.47            20558
            United Arab Emirates          88.73        0.58            59177
                          Guinea          88.69        0.64             7055
                           Ghana          88.63        0.50            33624
                         Andorra          88.53        5.73              907
                          Jordan          88.52        0.94             1176
           Saint Kitts and Nevis          88.24        0.00               17
                        Pakistan          87.87        2.13           274289
                            Chad          87.85        8.13              922
                          Uganda          87.41        0.18             1128
                            Iran          86.90        5.42           293606
                          Bhutan          86.87        0.00               99
             Trinidad and Tobago          86.49        5.41              148
                          Latvia          85.73        2.54             1219
                          Kuwait          85.52        0.68            64379
                        Barbados          85.45        6.36              110
                        Cameroon          84.97        2.29            17110
           Sao Tome and Principe          84.86        1.62              865
                         Vietnam          84.69        0.00              431
                    Burkina Faso          84.18        4.82             1100
                         Jamaica          83.70        1.17              853
                           Burma          83.43        1.71              350
                      Tajikistan          83.32        0.83             7235
                        Slovenia          83.04        5.56             2087
                    Saudi Arabia          82.90        1.03           268934
                         Georgia          81.09        1.41             1137
                           Italy          80.64       14.26           246286
                         Croatia          80.64        2.85             4881
                          Cyprus          80.38        1.79             1060
                       Lithuania          80.24        3.96             2019
                  Western Sahara          80.00       10.00               10
                         Burundi          79.63        0.26              378
                         Tunisia          79.52        3.44             1455
                         Morocco          79.25        1.51            20887
                         Uruguay          79.12        2.91             1202
                          Mexico          76.82       11.13           395489
                        Mongolia          76.82        0.00              289
                      Azerbaijan          76.34        1.39            30446
                      Luxembourg          76.33        1.77             6321
                            Mali          76.12        4.93             2513
                          Poland          75.70        3.86            43402
                          Brazil          75.61        3.59          2442375
                       Sri Lanka          75.61        0.39             2805
                        Maldives          75.60        0.45             3369
             Antigua and Barbuda          75.58        3.49               86
Saint Vincent and the Grenadines          75.00        0.00               52
                      Mauritania          74.95        2.51             6208
                         Hungary          74.84       13.40             4448
                        Slovakia          74.09        1.28             2181
                            Oman          74.01        0.51            77058
                    Sierra Leone          73.86        3.70             1783
                          Russia          73.74        1.63           816680
                         Czechia          73.65        2.40            15516
                           Nepal          73.35        0.26            18752
                       Nicaragua          72.46        3.14             3439
                         Eritrea          72.08        0.00              265
                       Guatemala          71.63        3.89            45309
                         Armenia          71.32        1.90            37390
                           Japan          70.55        3.20            31142
                        Portugal          70.33        3.42            50299

=======================================================
 Query 6 - Countries with Death Rate Above 10%
=======================================================
       country  death_rate  confirmed_cases  total_deaths
         Yemen       28.56             1691           483
United Kingdom       15.19           301708         45844
       Belgium       14.79            66428          9822
         Italy       14.26           246286         35112
        France       13.71           220352         30212
       Hungary       13.40             4448           596
   Netherlands       11.53            53413          6160
        Mexico       11.13           395489         44022
         Spain       10.44           272421         28432

          country  death_rate  confirmed_cases  total_deaths
0           Yemen       28.56             1691           483
1  United Kingdom       15.19           301708         45844
2         Belgium       14.79            66428          9822
3           Italy       14.26           246286         35112
4          France       13.71           220352         30212
5         Hungary       13.40             4448           596
6     Netherlands       11.53            53413          6160
7          Mexico       11.13           395489         44022
8           Spain       10.44           272421         28432

In [6]:
# ---- 6.5 Advanced SQL Queries ----

# Query 7 - Rank countries by confirmed cases using RANK() window function
# RANK() assigns a rank number to each country based on confirmed cases
run_query("""
    SELECT 
        "Country/Region"        AS country,
        "Confirmed"             AS confirmed_cases,
        RANK() OVER (
            ORDER BY "Confirmed" DESC
        )                       AS rank
    FROM country_wise
    LIMIT 10;
""", "Query 7 - Country Rankings by Confirmed Cases (RANK)")


# Query 8 - Using CTE to find countries above average confirmed cases
# CTE (Common Table Expression) is like a temporary table we create first
# then query from it
run_query("""
    WITH avg_cases AS (
        -- First calculate the average confirmed cases across all countries
        SELECT AVG("Confirmed") AS avg_confirmed
        FROM country_wise
    )
    -- Then find all countries above that average
    SELECT 
        "Country/Region"    AS country,
        "Confirmed"         AS confirmed_cases
    FROM country_wise, avg_cases
    WHERE "Confirmed" > avg_confirmed
    ORDER BY confirmed_cases DESC;
""", "Query 8 - Countries Above Average Confirmed Cases (CTE)")


# Query 9 - Daily new cases rolling 7 day average
# This smooths out daily spikes to show the real trend
run_query("""
    SELECT 
        "Date"                          AS date,
        "New cases"                     AS new_cases,
        ROUND(AVG("New cases") OVER (
            ORDER BY "Date"
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ), 0)                           AS rolling_7day_avg
    FROM day_wise
    ORDER BY "Date"
    LIMIT 20;
""", "Query 9 - Rolling 7-Day Average of New Cases")

=======================================================
 Query 7 - Country Rankings by Confirmed Cases (RANK)
=======================================================
       country  confirmed_cases  rank
            US          4290259     1
        Brazil          2442375     2
         India          1480073     3
        Russia           816680     4
  South Africa           452529     5
        Mexico           395489     6
          Peru           389717     7
         Chile           347923     8
United Kingdom           301708     9
          Iran           293606    10

=======================================================
 Query 8 - Countries Above Average Confirmed Cases (CTE)
=======================================================
       country  confirmed_cases
            US          4290259
        Brazil          2442375
         India          1480073
        Russia           816680
  South Africa           452529
        Mexico           395489
          Peru           389717
         Chile           347923
United Kingdom           301708
          Iran           293606
      Pakistan           274289
         Spain           272421
  Saudi Arabia           268934
      Colombia           257101
         Italy           246286
        Turkey           227019
    Bangladesh           226225
        France           220352
       Germany           207112
     Argentina           167416
        Canada           116458
          Iraq           112585
         Qatar           109597
     Indonesia           100303
         Egypt            92482

=======================================================
 Query 9 - Rolling 7-Day Average of New Cases
=======================================================
      date  new_cases  rolling_7day_avg
2020-01-22          0               0.0
2020-01-23         99              50.0
2020-01-24        287             129.0
2020-01-25        493             220.0
2020-01-26        684             313.0
2020-01-27        809             395.0
2020-01-28       2651             718.0
2020-01-29        588             802.0
2020-01-30       2068            1083.0
2020-01-31       1693            1284.0
2020-02-01       2111            1515.0
2020-02-02       4749            2096.0
2020-02-03       3100            2423.0
2020-02-04       4011            2617.0
2020-02-05       3745            3068.0
2020-02-06       3159            3224.0
2020-02-07       3532            3487.0
2020-02-08       2734            3576.0
2020-02-09       3027            3330.0
2020-02-10       2538            3249.0

          date  new_cases  rolling_7day_avg
0   2020-01-22          0               0.0
1   2020-01-23         99              50.0
2   2020-01-24        287             129.0
3   2020-01-25        493             220.0
4   2020-01-26        684             313.0
5   2020-01-27        809             395.0
6   2020-01-28       2651             718.0
7   2020-01-29        588             802.0
8   2020-01-30       2068            1083.0
9   2020-01-31       1693            1284.0
10  2020-02-01       2111            1515.0
11  2020-02-02       4749            2096.0
12  2020-02-03       3100            2423.0
13  2020-02-04       4011            2617.0
14  2020-02-05       3745            3068.0
15  2020-02-06       3159            3224.0
16  2020-02-07       3532            3487.0
17  2020-02-08       2734            3576.0
18  2020-02-09       3027            3330.0
19  2020-02-10       2538            3249.0